// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "node --import tsx prisma/seed.ts",
  },
  datasource: {
    // A fresh clone works without private configuration. DATABASE_URL remains
    // overridable for CI or a developer who wants a separate SQLite file.
    url: process.env["DATABASE_URL"] ?? "file:./dev.db",
  },
});
